## 1.1 pytorch基本元素操作

In [3]:
import torch

In [3]:
x=torch.empty(5,3)
print(x)

tensor([[5.2012e+22, 2.6684e-09, 8.3144e-07],
        [1.4580e-19, 1.1495e+24, 3.0881e+29],
        [1.5766e-19, 4.6304e+27, 7.2707e+31],
        [7.1536e+22, 3.3803e-18, 2.0552e+32],
        [1.8755e+28, 3.1093e-18, 5.2613e+34]])


In [4]:
x=torch.rand(5,3)
print(x)

tensor([[0.4487, 0.4409, 0.9421],
        [0.6390, 0.3357, 0.2013],
        [0.7388, 0.0150, 0.2222],
        [0.9233, 0.6864, 0.8502],
        [0.1544, 0.7905, 0.6710]])


In [4]:
x=torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [6]:
x = torch.tensor([2.5,3,5])
x

tensor([2.5000, 3.0000, 5.0000])

In [6]:
x = x.new_ones(5,3,dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [7]:
y = torch.randn_like(x,dtype=torch.float)
y

tensor([[ 0.4567, -0.8619, -0.6262],
        [-1.6389,  1.7488,  0.2464],
        [-0.2904,  0.4643, -1.2813],
        [ 0.0237, -0.8172,  0.5403],
        [-1.3896, -1.6678, -1.0059]])

In [20]:
y.size() 
# 元组类型

torch.Size([5, 3])

In [21]:
print('test')

test


## 1.2 pytorch基本运算操作

In [22]:
x+y

tensor([[ 1.2884,  1.7329, -0.2445],
        [ 1.9975,  2.0811, -0.3804],
        [-0.1424,  0.9535,  1.8246],
        [-0.3448,  1.5255,  1.2839],
        [ 0.4575,  2.4660,  2.0163]], dtype=torch.float64)

In [23]:
torch.add(x,y)

tensor([[ 1.2884,  1.7329, -0.2445],
        [ 1.9975,  2.0811, -0.3804],
        [-0.1424,  0.9535,  1.8246],
        [-0.3448,  1.5255,  1.2839],
        [ 0.4575,  2.4660,  2.0163]], dtype=torch.float64)

In [24]:
res = torch.empty(5,3)
torch.add(x,y,out=res)
res

tensor([[ 1.2884,  1.7329, -0.2445],
        [ 1.9975,  2.0811, -0.3804],
        [-0.1424,  0.9535,  1.8246],
        [-0.3448,  1.5255,  1.2839],
        [ 0.4575,  2.4660,  2.0163]])

In [25]:
y.add_(x)
y

tensor([[ 1.2884,  1.7329, -0.2445],
        [ 1.9975,  2.0811, -0.3804],
        [-0.1424,  0.9535,  1.8246],
        [-0.3448,  1.5255,  1.2839],
        [ 0.4575,  2.4660,  2.0163]])

In [27]:
y[:,1]

tensor([1.7329, 2.0811, 0.9535, 1.5255, 2.4660])

In [29]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8)
print(y.size(),z.size())


torch.Size([16]) torch.Size([2, 8])


In [33]:
x = torch.randn(1)
x.item()

-0.37768152356147766

In [34]:
# array 和 tensor 内存共享
a  = torch.ones(5)
b = a.numpy()
a.add_(1)
print(a)
print(b)


tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [35]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a,1,out=a)
print(a)
print(b)


[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [42]:
if torch.cuda.is_available():
    device = torch.device('cuda')
    x = torch.randn(2)
    y = torch.ones_like(x,device=device)
    x = x.to(device)
    z = x+y
    print(z)
    z = z.to('cpu')
    print(z)

tensor([-0.3042,  3.3037], device='cuda:0')
tensor([-0.3042,  3.3037])
