## 2. Autograd

神经网络本质上都是一个autograd package(自动求导工具包),提供了一个对Tensors上所有的操作进行自动微分的功能.

### tensor: 
- .requires_grad设置为True, 它将追踪在这个类上定义的所有操作. 当代码要进行反向传播的时候, 
- .backward()就可以自动计算所有的梯度. 
- 在这个Tensor上的所有梯度将被累加进属性.grad中.
- .grad_fn属性, 代表引用了哪个具体的Function创建了该Tensor.
- 终止一个Tensor在计算图中的追踪回溯, 只需要执行.detach()就可以将该Tensor从计算图中撤下, 在未来的回溯计算中也不会再计算该Tensor.
- 也可以采用代码块的方式with torch.no_grad().

In [1]:
import torch
x = torch.ones(2,2,requires_grad=True)
y = x+2
print(y)
print(y.grad_fn)
z = x*2
print(z.grad_fn)
t = y*y*3
out = t.mean()
print(t,out)
out = torch.rand(4)
print(out.requires_grad)
out.requires_grad_(True)
b = (out*out).sum()
print(out.requires_grad)
print(b.grad_fn)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)
False
True


In [5]:
import torch
x = torch.ones(2,2,requires_grad=True)
y = x+2
# z = y*y*3
out = y.mean()
print(x)
print(y)
# print(z)
print(out)
out.backward()
# y.backward()
print(x.grad)
print(y.grad)
# print(z.grad)
print(out.grad)
print(x.requires_grad)
print(y.requires_grad)
with torch.no_grad():
    print(x.requires_grad)
y = x.detach()
print(x.requires_grad)
print(y.requires_grad)
print(x.eq(y).all())

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
tensor(3., grad_fn=<MeanBackward0>)
tensor([[0.2500, 0.2500],
        [0.2500, 0.2500]])
None
None
True
True
True
True
False
tensor(True)
